// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.example.demo;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;

@Servant
public interface MessageServant {

	public boolean send(String msg);

	public String encode(String sign);

	public boolean encodeWithSend(String msg, String sign);
}
