// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.example.tarsmqserver.service.rsaserver;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class CipherPrxCallback extends TarsAbstractCallback {

	public abstract void callback_getPublicKey(boolean ret, String pubKey);

	public abstract void callback_genKey(boolean ret, String priKey, String pubKey);

	public abstract void callback_encodeByPrivateKey(boolean ret, String enStr);

	public abstract void callback_encodeByPublicKey(boolean ret, String enStr);

	public abstract void callback_decodeByPrivateKey(boolean ret, String plain);

	public abstract void callback_decodeByPublicKey(boolean ret, String plain);

	public abstract void callback_sign(boolean ret, String signStr);

	public abstract void callback_verify(boolean ret);

}
