// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.example.tarsmqserver.service.rsaserver;

public enum KeyType {

	PASSWORD(0),
	PLAIN(1),
	SIGN(2),
	JWT(3);

	private final int value;

	private KeyType(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static KeyType convert(int value) {
		for(KeyType v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
