// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.example.client.service.demo;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class MessagePrxCallback extends TarsAbstractCallback {

	public abstract void callback_send(boolean ret);

	public abstract void callback_encode(String ret);

	public abstract void callback_encodeWithSend(boolean ret);
}
